# arc/aspek.py

aspects = {
    'kebersihan': [
        'kotor', 'bersih', 'sampah', 'jorok', 'bau', 'kumuh', 'higienis', 'sanitasi', 'rapi', 
        'limbah', 'polusi', 'debu', 'terawat', 'terkontaminasi', 'mengapung', 'pantai kotor',
        'plastik', 'steril', 'sehat', 'pembersihan', 'kebersihan terjaga', 'bersih sekali',
        'sampah berserakan', 'bau busuk', 'bau amis', 'bangkai', 'daun kering', 'karang mati',
        'pasir bersih', 'air jernih', 'transparan', 'keruh', 'berminyak', 'berlumut',
        'alga', 'ramah lingkungan', 'eco-friendly', 'zero waste', 'sampah organik',
        'sampah anorganik', 'tempat sampah', 'penghijauan', 'hijau', 'asri', 'tercemar',
        'kontaminasi', 'polutan', 'zat berbahaya', 'bakteri', 'kuman', 'penyakit',
        'kesehatan', 'kebersihan pantai', 'kebersihan laut', 'kebersihan fasilitas',
        'menjaga kebersihan', 'peduli lingkungan', 'kesadaran lingkungan'
        'butek', 'air butek', 'kotor', 'lumpur', 'air surut', 'pasir putih', 'alami',
        'abrasi', 'hancur', 'puing', 'hun kunjung', 'rawat', 'awat', 'kelola',
        'terbelengkai', 'bengkalai', 'laku', 'moga baik', 'benah', 'terawat baik',
        'bersih', 'jaga', 'lestari', 'alam guru baik', 'alam tidak tipu'
    ],
    
'keamanan': [
    'aman', 'bahaya', 'rawan', 'penjaga', 'satpam', 'rampok', 'tidak aman', 'kriminalitas',
    'pencurian', 'penjagaan', 'satpam', 'pengawasan', 'CCTV', 'patroli', 'kekerasan',
    'ancaman', 'proteksi', 'keamanan terjaga', 'aman untuk keluarga', 'aman untuk anak',
    'petugas keamanan', 'lifeguard', 'penjaga pantai', 'penyelamat', 'pemantauan',
    'zona aman', 'area berbahaya', 'arus deras', 'ombak besar', 'jurang', 'berkarang',
    'berlubang', 'hewan berbahaya', 'ubin pecah', 'licin', 'gelap', 'penerangan',
    'lampu', 'tersesat', 'tanda peringatan', 'rambu-rambu', 'panduan keselamatan',
    'alat keselamatan', 'pelampung', 'p3k', 'posko keamanan', 'hotline darurat',
    'evakuasi', 'bencana', 'tsunami', 'banjir', 'pencurian barang', 'pencopetan',
    'pemalakan', 'preman', 'penodongan', 'teror', 'molestasi', 'pelecehan',
    'keamanan kendaraan', 'parkir aman', 'aman malam hari', 'keamanan wanita',
    'zona khusus', 'pengamanan', 'security',
    'sepi', 'tenang', 'ayem', 'damai', 'nyaman', 'tidak ramai', 'sunyi',
    'ramai', 'padat', 'crowded', 'hiruk pikuk', 'ribut', 'bising',
    'sunyi senyap', 'hening', 'tenteram', 'adem', 'sejuk', 'angin sepoi',
    'nyamuk', 'serangga', 'binatang', 'monyet', 'hutan', 'magrove',
    'tangkai', 'pagar', 'gembok', 'tutup', 'buka', 'larang', 'terlarang',
    'jauh', 'terpencil', 'tersembunyi', 'hidden', 'gems', 'tersembunyi'
],

'keindahan': [
    'bagus', 'keren', 'pemandangan', 'view', 'indah', 'cantik', 'menarik', 'estetis',
    'artistik', 'dekorasi', 'serasi', 'elegan', 'panorama', 'tata ruang', 'visual',
    'eksotis', 'memukau', 'menakjubkan', 'spektakuler', 'fantastis', 'luar biasa',
    'sunset', 'sunrise', 'matahari terbenam', 'matahari terbit', 'pantai indah',
    'pasir putih', 'pasir keemasan', 'air biru', 'air jernih', 'ombak tenang',
    'ombak besar', 'tebing', 'karang', 'batu karang', 'formasi batuan', 'vegetasi',
    'pohon kelapa', 'hutan pantai', 'mangrove', 'terumbu karang', 'biota laut',
    'warna-warni', 'kontras', 'harmonis', 'alami', 'alami sekali', 'alami banget',
    'tidak terawat', 'terawat baik', 'landscape', 'pemandangan laut', 'pemandangan darat',
    'horizon', 'cahaya', 'siluet', 'refleksi', 'fotogenik', 'instagramable',
    'spot foto', 'angle bagus', 'pengaturan cahaya', 'warna alam', 'senja',
    'biru langit', 'hijau pepohonan', 'coklat tebing', 'putih pasir',
    'keindahan alam', 'keindahan buatan', 'taman', 'hiasan', 'lampion',
    'patung', 'ukiran', 'arsitektur', 'bangunan tradisional', 'perahu',
    'perahu tradisional', 'perahu nelayan', 'jaring', 'aktivitas nelayan',
    'aktivitas tradisional', 'budaya lokal', 'kearifan lokal',
    'eksotis', 'alam', 'natural', 'asri', 'teduh', 'rindang', 'pohon',
    'cemara udang', 'pohon cemara', 'mangrove', 'hutan bakau', 'karang',
    'batu', 'tebing', 'ombak', 'gelombang', 'laut', 'pantai', 'pasir',
    'hampar', 'luas', 'lebar', 'sempit', 'landai', 'curam',
    'matahari benam', 'sunset', 'matahari terbit', 'sunrise', 'senja',
    'pagi', 'sore', 'malam', 'cahaya', 'siluet', 'pandang', 'view',
    'latar', 'background', 'jembatan suramadu', 'suramadu', 'jembatan',
    'laut biru', 'air bening', 'jernih', 'transparan', 'bersih',
    'pasir lembut', 'halus', 'kasar', 'berbatu', 'berkarang',
    'estetik', 'instagramable', 'foto', 'spot foto', 'swafoto',
    'hunting foto', 'angle', 'pengambilan gambar', 'visual',
    'memukau', 'menakjubkan', 'spektakuler', 'fantastis', 'luar biasa',
    'cakep', 'kece', 'bagus', 'keren', 'wow', 'amazing', 'awesome',
    'ajib', 'mantap', 'top', 'the best', 'sempurna', 'paripurna',
    'surga', 'surga dunia', 'pesona', 'pesona alam', 'keajaiban',
    'keajaiban alam', 'fenomena alam', 'unik', 'khas', 'spesial',
    'legendaris', 'ikonik', 'tradisional', 'budaya', 'kearifan lokal',
    'sejarah', 'bersejarah', 'peninggalan', 'tinggalan', 'belanda',
    'kolonial', 'mercsuar', 'menara suar', 'benteng', 'goa', 'gua',
    'karst', 'kapur', 'tambang', 'bukit kapur', 'jaddih'
],

'fasilitas': [
    'warung', 'tempat', 'gazebo', 'kursi', 'pondok', 'fasilitas lengkap',
    'minim fasilitas', 'toilet', 'parkir', 'wifi', 'mushola', 'ruang tunggu',
    'AC', 'peralatan', 'loker', 'lift', 'rusak', 'tidak berfungsi',
    'tempat istirahat', 'payung pantai', 'kursi pantai', 'tikar', 'tenda',
    'bilik ganti', 'bilik mandi', 'shower', 'air tawar', 'kamar mandi umum',
    'toilet umum', 'toilet bersih', 'toilet kotor', 'air mengalir',
    'tempat sampah', 'tempat cuci kaki', 'tempat wudhu', 'mushola bersih',
    'tempat ibadah', 'area parkir', 'parkir luas', 'parkir sempit',
    'parkir berbayar', 'parkir gratis', 'parkir motor', 'parkir mobil',
    'parkir bus', 'area piknik', 'meja piknik', 'bangku', 'permainan anak',
    'playground', 'area olahraga', 'voli pantai', 'futsal', 'perahu sewa',
    'alat snorkeling', 'alat selam', 'ban pelampung', 'pelampung anak',
    'penyewaan alat', 'water sport', 'jet ski', 'banana boat', 'parasailing',
    'warung makan', 'kafe', 'restoran', 'kedai', 'minuman', 'makanan tradisional',
    'oleh-oleh', 'souvenir', 'toko suvenir', 'penjual aksesoris',
    'penjual makanan', 'penjual minuman', 'kelapa muda', 'ikan bakar',
    'seafood', 'tempat duduk', 'tempat berteduh', 'papan informasi',
    'peta lokasi', 'brochure', 'panduan wisata', 'pemandu wisata',
    'tour guide', 'information center', 'pos informasi', 'pusat informasi',
    'first aid', 'klinik', 'puskesmas', 'apotik', 'ambulans',
    'tempat penitipan barang', 'locker', 'charging station', 'colokan listrik',
    'listrik', 'generator', 'penerangan', 'lampu jalan', 'lampu taman',
    'sound system', 'panggung', 'area pertunjukan', 'panggung hiburan',
    'area camping', 'tempat berkemah', 'area BBQ', 'tempat memasak',
    'air bersih', 'air minum', 'dispenser', 'refill air', 'galon',
    'toilet', 'wc', 'kamar mandi', 'bilik mandi', 'bilik ganti',
    'shower', 'air tawar', 'air bersih', 'air mengalir',
    'tempat wudhu', 'mushola', 'masjid', 'tempat ibadah',
    'parkir', 'tempat parkir', 'area parkir', 'parkir mobil',
    'parkir motor', 'parkir bus', 'parkir gratis', 'parkir berbayar',
    'retribusi parkir', 'biaya parkir', 'tiket parkir',
    'warung', 'kios', 'toko', 'kedai', 'cafe', 'restoran',
    'rumah makan', 'warung makan', 'food court', 'pusat kuliner',
    'penjual makanan', 'penjual minuman', 'jajan', 'kuliner',
    'makanan khas', 'minuman khas', 'oleh-oleh', 'souvenir',
    'cenderamata', 'kerajinan', 'hasil tangan', 'lokal',
    'perahu', 'boat', 'kapal', 'speedboat', 'ferry', 'transportasi air',
    'sewa perahu', 'sewa kapal', 'sewa boat', 'sewa speedboat',
    'transportasi darat', 'ojek', 'bentor', 'becak', 'andong',
    'rental motor', 'rental mobil', 'sewa kendaraan',
    'papan informasi', 'papan petunjuk', 'signage', 'rambu',
    'petunjuk arah', 'denah', 'peta', 'maps', 'google maps',
    'tour guide', 'pemandu wisata', 'pemandu lokal', 'guide',
    'informasi', 'pusat informasi', 'pos informasi', 'info center',
    'first aid', 'P3K', 'klinik', 'puskesmas', 'rumah sakit',
    'apotik', 'obat-obatan', 'ambulans', 'evakuasi',
    'area bermain', 'playground', 'taman bermain', 'permainan anak',
    'ayunan', 'perosotan', 'jungkat-jungkit', 'bak pasir',
    'kolam renang', 'waterpark', 'taman air', 'water boom',
    'banana boat', 'jet ski', 'parasailing', 'snorkeling',
    'diving', 'selam', 'peralatan snorkeling', 'peralatan selam',
    'sewa alat', 'rental equipment', 'water sport', 'olahraga air',
    'area olahraga', 'lapangan', 'futsal', 'voli', 'bulutangkis',
    'sepeda', 'sewa sepeda', 'rental sepeda', 'sepeda air',
    'area camping', 'tempat berkemah', 'camping ground',
    'tenda', 'sewa tenda', 'rental tenda', 'peralatan camping',
    'api unggun', 'bonfire', 'BBQ', 'barbecue', 'pemanggang',
    'listrik', 'stop kontak', 'colokan', 'charging station',
    'pengisian daya', 'power bank', 'generator', 'sumber listrik',
    'penerangan', 'lampu', 'lampu jalan', 'lampu taman',
    'lampu pantai', 'penerangan malam', 'cahaya',
    'sound system', 'pengeras suara', 'musik', 'hiburan',
    'panggung', 'stage', 'pertunjukan', 'show', 'entertainment',
    'area pertemuan', 'meeting point', 'tempat kumpul',
    'gazebo', 'pendopo', 'balai', 'aula', 'ruang pertemuan',
    'tempat duduk', 'kursi', 'bangku', 'meja', 'tikar',
    'alas duduk', 'tempat bersantai', 'area relaksasi',
    'payung', 'parasol', 'tempat teduh', 'pelindung panas',
    'angin', 'kipas angin', 'AC', 'pendingin ruangan',
    'heater', 'pemanas', 'perapian', 'fireplace'
],

'aksesibilitas': [
    'macet', 'rute', 'jalur', 'mudah', 'akses mudah', 'akses sulit',
    'dekat', 'jauh', 'transportasi', 'jalur pedestrian', 'ramah difabel',
    'jalan', 'halte', 'kemacetan', 'lokasi strategis', 'mudah dijangkau',
    'akses jalan', 'jalan bagus', 'jalan rusak', 'jalan berlubang',
    'jalan sempit', 'jalan lebar', 'jalan beraspal', 'jalan tanah',
    'jalan berbatu', 'akses kendaraan', 'mobil pribadi', 'motor',
    'bus', 'angkot', 'angkutan umum', 'taksi', 'ojek', 'ojek online',
    'transportasi online', 'grab', 'gojek', 'travel', 'shuttle',
    'bus wisata', 'parkir luas', 'terminal', 'stasiun', 'pelabuhan',
    'dermaga', 'penginapan dekat', 'hotel dekat', 'villa dekat',
    'homestay dekat', 'penginapan terjangkau', 'akomodasi',
    'transportasi lokal', 'perahu antar', 'speedboat', 'kapal',
    'ferry', 'penyeberangan', 'jembatan', 'akses dari kota',
    'akses dari bandara', 'akses dari stasiun', 'akses dari terminal',
    'petunjuk arah', 'signage', 'penunjuk jalan', 'papan penunjuk',
    'google maps', 'maps akurat', 'sulit ditemukan', 'tersembunyi',
    'remote', 'terpencil', 'terisolasi', 'akses terbatas',
    'akses 24 jam', 'buka jam', 'jam operasional', 'tiket masuk',
    'biaya masuk', 'parkir gratis', 'retribusi', 'tiket terusan',
    'paket wisata', 'tur', 'guide lokal', 'pemandu lokal',
    'bahasa Inggris', 'multibahasa', 'penjelasan', 'informasi akses',
    'akses difabel', 'kursi roda', 'jalan landai', 'toilet difabel',
    'parkir difabel', 'fasilitas difabel', 'akses lansia',
    'akses anak-anak', 'akses keluarga', 'ramah keluarga',
    'ramah anak', 'area bermain', 'area menyusui', 'ruang keluarga',
    'lokasi', 'tempat', 'area', 'zona', 'kawasan', 'wilayah',
    'daerah', 'kabupaten', 'kecamatan', 'desa', 'dusun',
    'alamat', 'titik', 'koordinat', 'GPS', 'latitude', 'longitude',
    'jarak', 'dekat', 'jauh', 'sekitar', 'sekitaran', 'perjalanan',
    'waktu tempuh', 'jam perjalanan', 'menit perjalanan',
    'transportasi', 'angkutan', 'kendaraan', 'mobil', 'motor',
    'bus', 'angkot', 'bemo', 'truk', 'travel', 'shuttle',
    'taksi', 'ojek', 'online', 'grab', 'gojek', 'maxim',
    'perahu', 'kapal', 'speedboat', 'ferry', 'ro-ro', 'penyeberangan',
    'dermaga', 'pelabuhan', 'terminal', 'stasiun', 'halte',
    'bandara', 'airport', 'stasiun kereta', 'train station',
    'terminal bus', 'bus station', 'shelter', 'perhentian',
    'jalan', 'jalan raya', 'jalan tol', 'jalan provinsi',
    'jalan kabupaten', 'jalan desa', 'jalan setapak', 'jalan tanah',
    'jalan batu', 'jalan beraspal', 'jalan beton', 'jalan makadam',
    'jalan licin', 'jalan curam', 'jalan landai', 'jalan sempit',
    'jalan lebar', 'jalan berlubang', 'jalan rusak', 'jalan bagus',
    'jalan mulus', 'jalan halus', 'jalan kasar', 'jalan berbatu',
    'akses', 'mudah diakses', 'sulit diakses', 'terjangkau',
    'terisolasi', 'terpencil', 'tersembunyi', 'remote',
    'strategis', 'pusat', 'pinggir', 'tepi', 'ujung', 'sudut',
    'peta', 'maps', 'google maps', 'waze', 'petunjuk',
    'arah', 'petunjuk arah', 'signage', 'rambu', 'papan',
    'penunjuk jalan', 'denah', 'layout', 'tata letak',
    'parkir', 'tempat parkir', 'area parkir', 'parkir luas',
    'parkir sempit', 'parkir gratis', 'parkir berbayar',
    'retribusi parkir', 'biaya parkir', 'tiket parkir',
    'parkir mobil', 'parkir motor', 'parkir bus',
    'parkir sepeda', 'parkir roda dua', 'parkir roda empat',
    'tiket', 'karcis', 'biaya masuk', 'retribusi', 'harga tiket',
    'gratis', 'free', 'berbayar', 'bayar', 'murah', 'mahal',
    'terjangkau', 'worth it', 'worth the price', 'harga pantas',
    'overpriced', 'mahal banget', 'ngotak', 'tidak wajar',
    'wajar', 'reasonable', 'fair', 'adil', 'sesuai',
    'jam', 'waktu', 'buka', 'tutup', 'operasional',
    'jam buka', 'jam tutup', '24 jam', 'siang', 'malam',
    'pagi', 'sore', 'senja', 'dini hari', 'subuh',
    'high season', 'low season', 'musim', 'season',
    'ramai', 'sepi', 'crowded', 'quiet', 'sunyi',
    'liburan', 'weekend', 'weekdays', 'hari kerja',
    'hari libur', 'lebaran', 'natal', 'tahun baru',
    'musim hujan', 'musim kemarau', 'cuaca', 'weather',
    'panas', 'dingin', 'hujan', 'cerah', 'mendung',
    'angin', 'badai', 'storm', 'typhoon', 'cyclone',
    'ombak', 'gelombang', 'pasang', 'surut', 'air pasang',
    'air surut', 'high tide', 'low tide', 'tide'
]}