kamus_slang = {
    'ad': 'ada', 'adem': 'dingin', 'ae': 'saja', 'aga': 'agak', 'agk': 'agak',
    'airasin': 'air asin', 'aja': 'saja', 'ajalahhh': 'saja lah', 'ajasi': 'saja sih',
    'ama': 'sama', 'anj': 'anjing', 'apalgi': 'apalagi', 'apesiiiigilak': 'apa sih gila',
    'apik': 'bagus', 'ato': 'atau', 'b': 'biasa', 'b aja': 'biasa saja',
    'bab': 'buang air besar', 'bak': 'buang air kecil', 'bangettt': 'banget',
    'bangett': 'banget', 'bangeeet': 'banget', 'bangetttt': 'banget', 'bangus': 'bagus',
    'banyka': 'banyak', 'basah2': 'basah-basah', "be'e": 'buang air besar', 'begtu': 'begitu',
    'belom': 'belum', 'bener': 'benar', 'beneran': 'benaran', 'ber teduh': 'berteduh',
    'berasa': 'terasa', 'bet': 'banget', 'bgd': 'banget', 'bgs': 'bagus',
    'bgt': 'banget', 'bgtt': 'banget', 'bgus': 'bagus', 'bikin': 'membuat',
    'bilas nya': 'bilasnya', 'bingit': 'banget', 'blm': 'belum', 'bnget': 'banget',
    'bngt': 'banget', 'bnyk': 'banyak', 'bocil': 'anak kecil', 'bolehlah': 'boleh lah',
    'brani': 'berani', 'brasa': 'terasa', 'brjualan': 'berjualan', 'brkunjung': 'berkunjung',
    'bs': 'bisa', 'bsnget': 'banget', 'bt': 'buat', 'buagus': 'bagus',
    'buat': 'untuk', 'buangettt': 'banget', 'buanyak': 'banyak', 'buk': 'ibu',
    'byk': 'banyak', 'byr': 'bayar', 'cmn': 'cuma', 'cm': 'cuma', 'cma': 'cuma',
    'cocoknya': 'seharusnya', 'cpt': 'cepat', 'cukupkah': 'cukup', 'cuman': 'cuma',
    'd': 'di', 'deket': 'dekat', 'dg': 'dengan', 'dgn': 'dengan',
    'disini': 'di sini', 'disitu': 'di situ', 'dk': 'dekat', 'dket': 'dekat',
    'dkt': 'dekat', 'dl': 'dulu', 'dlu': 'dulu', 'dluw': 'dulu',
    'dmn': 'di mana', 'dmn2': 'di mana-mana', 'dr': 'dari', 'dri': 'dari',
    'dsini': 'di sini', 'dsitu': 'di situ', 'dtg': 'datang', 'duren': 'durian',
    'eek': 'buang air besar', 'em': 'memang', 'emang': 'memang', 'enakx': 'enaknya',
    'engga': 'tidak', 'enggak': 'tidak', 'exotis': 'eksotis', 'foto2': 'foto-foto',
    'ga': 'tidak', 'gabole': 'tidak boleh', 'gac': 'tidak', 'gada': 'tidak ada',
    'gaes': 'teman-teman', 'gais': 'teman-teman', 'gak': 'tidak', 'gampang': 'mudah',
    'gapapa': 'tidak apa-apa', 'gasebo': 'gazebo', 'gatau': 'tidak tahu', 'gc': 'tidak',
    'gede2': 'besar-besar', 'ges': 'teman-teman', 'gimana': 'bagaimana', 'gini': 'begini',
    'gitu': 'begitu', 'gitu2': 'begitu-begitu', 'gk': 'tidak', 'gmn': 'bagaimana',
    'gpp': 'tidak apa-apa', 'gratisss': 'gratis', 'gretong': 'gratis', 'gue': 'saya',
    'gw': 'saya', 'hbs': 'habis', 'healing2': 'rekreasi', 'htm': 'harga tiket masuk',
    'jd': 'jadi', 'jg': 'juga', 'jgn': 'jangan', 'jl': 'jalan', 'jln': 'jalan',
    'joss': 'bagus', 'jukir': 'juru parkir', 'k': 'ke', 'kak': 'kakak',
    'kalo': 'kalau', 'karna': 'karena', 'kayak': 'seperti', 'kayaknya': 'sepertinya',
    'kbersihannya': 'kebersihannya', 'kcil': 'kecil', 'kek': 'seperti', 'kenak': 'kena',
    'kesana': 'ke sana', 'kesini': 'ke sini', 'ketagihan': 'kecanduan', 'klo': 'kalau',
    'klrga': 'keluarga', 'klu': 'kalau', 'klw': 'kalau', 'km': 'kamar mandi',
    'knp': 'kenapa', 'kok': 'kenapa', 'krg': 'kurang', 'krn': 'karena',
    'kurg': 'kurang', 'kurleb': 'kurang lebih', 'kyk': 'seperti', 'laenya': 'lainnya',
    'lg': 'lagi', 'lgsg': 'langsung', 'liat': 'lihat', 'luama': 'lama',
    'lumayanlah': 'lumayan lah', 'mah': 'saja', 'malah': 'justru', 'malem': 'malam',
    'mamin': 'makan minum', 'mantai': 'ke pantai', 'mantab': 'mantap', 'mantul': 'mantap betul',
    'masi': 'masih', 'masuknya': 'masuk', 'maybe': 'mungkin', 'mck': 'mandi cuci kakus',
    'mehong': 'mahal', 'mending': 'lebih baik', 'mgkin': 'mungkin', 'mksih': 'terima kasih',
    'mlh': 'malah', 'mlm': 'malam', 'mncari': 'mencari', 'mnt': 'menit',
    'mnju': 'menuju', 'msh': 'masih', 'muahal': 'mahal', 'mumer': 'murah meriah',
    'murce': 'murah', 'n': 'dan', 'nda': 'tidak', 'ndak': 'tidak',
    'neduh': 'berteduh', 'next time': 'lain kali', 'ngadem': 'mendinginkan diri', 'nggak': 'tidak',
    'ngk': 'tidak', 'ngopi': 'minum kopi', 'ntr': 'nanti', 'nyampek': 'sampai',
    'nyantai': 'santai', 'nyore': 'bersantai sore', 'oiya': 'oh iya', 'oke': 'ok',
    'org': 'orang', 'orng': 'orang', 'overall': 'secara keseluruhan', 'pas': 'saat',
    'pdhl': 'padahal', 'pe': 'per', 'perorg': 'per orang', 'pict': 'foto',
    'pingin': 'ingin', 'pk': 'pukul', 'pls': 'tolong', 'pol': 'banget',
    'polll': 'banget', 'pr': 'pekerjaan rumah', 'privat': 'pribadi', 'private': 'pribadi',
    'puas2in': 'puas-puasin', 'puwwanaasssss': 'panas', 'q': 'saya', 'r2': 'roda dua',
    'r4': 'roda empat', 'rame': 'ramai', 'rame2': 'ramai-ramai', 'rb': 'ribu',
    'rekomen': 'rekomendasi', 'rekomended': 'direkomendasikan', 'recomend': 'rekomendasi',
    'recommended': 'direkomendasikan', 'sampe': 'sampai', 'sampek': 'sampai', 'sbrnrnya': 'sebenarnya',
    'sdh': 'sudah', 'se adany': 'seadanya', 'sebrang': 'seberang', 'sekali': 'banget',
    'selfi': 'swafoto', 'selfi2': 'foto-foto', 'semrawut': 'berantakan', 'seneng': 'senang',
    'serebu': 'seribu', 'seru': 'menyenangkan', 'sih': 'sih', 'skali': 'sekali',
    'skalian': 'sekalian', 'skrg': 'sekarang', 'sm': 'sama', 'smg': 'semoga',
    'smoga': 'semoga', 'smp': 'sampai', 'sndiri': 'sendiri', 'sore2': 'sore-sore',
    'sore"': 'sore-sore', 'sorenya': 'sore', 'sperti': 'seperti', 'spot2': 'spot-spot',
    'sprti': 'seperti', 'spt': 'seperti', 'spy': 'supaya', 'srby': 'surabaya',
    'sby': 'surabaya', 'sy': 'saya', 'sya': 'saya', 't4': 'tempat', 'tau': 'tahu',
    'tbtb': 'tiba-tiba', 'td': 'tadi', 'tdk': 'tidak', 'telat': 'terlambat',
    'thanks': 'terima kasih', 'th': 'tahun', 'thn': 'tahun', 'tipis2': 'tipis-tipis',
    'tiptip': 'tipis-tipis', 'tk': 'tidak', 'tlng': 'tolong', 'tlong': 'tolong',
    'tmpat': 'tempat', 'tmpt': 'tempat', 'to': 'untuk', 'tp': 'tapi',
    'tpi': 'tapi', 'trjaga': 'terjaga', 'trmsuk': 'termasuk', 'trs': 'terus',
    'trsembunyi': 'tersembunyi', 'trus': 'terus', 'trutama': 'terutama', 'ttp': 'tetap',
    'u': 'untuk', 'udh': 'sudah', 'ujung2': 'ujung-ujungnya', 'utk': 'untuk',
    'view': 'pemandangan', 'viewnya': 'pemandangannya', 'weekend': 'akhir pekan', 'weekday': 'hari kerja',
    'wort it': 'sepadan', 'worth it': 'sepadan', 'woww': 'wow', 'wrng': 'warung',
    'ya': 'iya', 'yaa': 'iya', 'yah': 'iya', 'yg': 'yang', 'yh': 'iya'
}

# Menggabungkan kamus Inggris ke kamus slang
kamus_inggris = {
    'beach': 'pantai', 'beautiful': 'indah', 'best': 'terbaik', 'clean': 'bersih',
    'cool': 'keren', 'dirty': 'kotor', 'enjoy': 'menikmati', 'free': 'gratis',
    'good': 'bagus', 'great': 'hebat', 'holiday': 'liburan', 'nice': 'bagus',
    'private': 'pribadi', 'quiet': 'tenang', 'really': 'sangat', 'spot': 'tempat',
    'sunset': 'matahari terbenam', 'sunrise': 'matahari terbit', 'trash': 'sampah',
    'view': 'pemandangan', 'very': 'sangat', 'worth it': 'sepadan'
}

kamus_slang.update(kamus_inggris) # Menggabungkan kedua kamus